version: '3.1'

services:
  
  # proxysql
  proxysql:
    image: perconalab/proxysql
    networks:
      # galera network is a private network where all containers in swarm can connect
      - galera
      
      # using "outside" net enable to access proxysql from other containers or clients external from galera net, like mysql client.
      - outside
    ports:
      - "3306:3306"
      - "6032:6032"
    env_file: proxysql.env
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=proxysql]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == manager]

  # service discovery
  galera_etcd:
    image: quay.io/coreos/etcd
    command:  etcd
    volumes:
      # note: to test on windows change the path to this
      #- ./usr/share/ca-certificates/:/etc/ssl/certs
      - /usr/share/ca-certificates/:/etc/ssl/certs
    env_file: etcd.env
    networks:
      - galera
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # mysql database cluster
  percona-xtradb-cluster:
    image: percona/percona-xtradb-cluster:5.7
    networks:
      - galera
    env_file: galera.env
    volumes:
      - data:/var/lib/mysql
    deploy:
      mode: global
      labels: [APP=pxc]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == worker]
        
volumes:
  data:
  
networks:
  outside:
  galera:
    # Use a custom driver
    driver: overlay
    internal: true
    ipam:
      driver: default
      config:
       - subnet: 10.20.1.0/24
       
    
